export const MENU_BAR = {
  SWITCH_MENU: 'SWITCH_MENU'
}

export const SEARCH = {
  SWITCH_SEARCH_MENU: 'SWITCH_SEARCH_MENU',
  SEARCH_REQUEST: 'SEARCH_REQUEST',
  SEARCH_SUCCESS: 'SEARCH_SUCCESS',
  SEARCH_FAILURE: 'SEARCH_FAILURE',
  SEARCH_LOAD_MORE_REQUEST: 'SEARCH_LOAD_MORE_REQUEST',
  SEARCH_LOAD_MORE_SUCCESS: 'SEARCH_LOAD_MORE_SUCCESS',
  SEARCH_LOAD_MORE_FAILURE: 'SEARCH_LOAD_MORE_FAILURE',
}

export const PLAYER = {
  FETCH_PLAYBACK_DATA_REQUEST: 'FETCH_PLAYBACK_DATA_REQUEST',
  FETCH_PLAYBACK_DATA_SUCCESS: 'FETCH_PLAYBACK_DATA_SUCCESS',
  FETCH_PLAYBACK_DATA_FAILURE: 'FETCH_PLAYBACK_DATA_FAILURE',
  FETCH_AVAILABLE_DEVICES_REQUEST: 'FETCH_AVAILABLE_DEVICES_REQUEST',
  FETCH_AVAILABLE_DEVICES_SUCCESS: 'FETCH_AVAILABLE_DEVICES_SUCCESS',
  FETCH_AVAILABLE_DEVICES_FAILURE: 'FETCH_AVAILABLE_DEVICES_FAILURE',
  TRANSFER_PLAYBACK_REQUEST: 'TRANSFER_PLAYBACK_REQUEST',
  TRANSFER_PLAYBACK_SUCCESS: 'TRANSFER_PLAYBACK_SUCCESS',
  TRANSFER_PLAYBACK_FAILURE: 'TRANSFER_PLAYBACK_FAILURE',
  START_PLAYBACK_REQUEST: 'START_PLAYBACK_REQUEST',
  START_PLAYBACK_SUCCESS: 'START_PLAYBACK_SUCCESS',
  START_PLAYBACK_FAILURE: 'START_PLAYBACK_FAILURE',
  PAUSE_PLAYBACK_REQUEST: 'PAUSE_PLAYBACK_REQUEST',
  PAUSE_PLAYBACK_SUCCESS: 'PAUSE_PLAYBACK_SUCCESS',
  PAUSE_PLAYBACK_FAILURE: 'PAUSE_PLAYBACK_FAILURE',
  TOGGLE_SHUFFLE_REQUEST: 'TOGGLE_SHUFFLE_REQUEST',
  TOGGLE_SHUFFLE_SUCCESS: 'TOGGLE_SHUFFLE_SUCCESS',
  TOGGLE_SHUFFLE_FAILURE: 'TOGGLE_SHUFFLE_FAILURE',
  SET_REPEAT_MODE_REQUEST: 'SET_REPEAT_MODE_REQUEST',
  SET_REPEAT_MODE_SUCCESS: 'SET_REPEAT_MODE_SUCCESS',
  SET_REPEAT_MODE_FAILURE: 'SET_REPEAT_MODE_FAILURE',
  SKIP_NEXT_REQUEST: 'SKIP_NEXT_REQUEST',
  SKIP_NEXT_SUCCESS: 'SKIP_NEXT_SUCCESS',
  SKIP_NEXT_FAILURE: 'SKIP_NEXT_FAILURE',
  SKIP_PREVIOUS_REQUEST: 'SKIP_PREVIOUS_REQUEST',
  SKIP_PREVIOUS_SUCCESS: 'SKIP_PREVIOUS_SUCCESS',
  SKIP_PREVIOUS_FAILURE: 'SKIP_PREVIOUS_FAILURE',
  PLAY_REQUEST: 'PLAY_REQUEST',
  PLAY_SUCCESS: 'PLAY_SUCCESS',
  PLAY_FAILURE: 'PLAY_FAILURE',
  SET_VOLUME_REQUEST: 'SET_VOLUME_REQUEST',
  SET_VOLUME_SUCCESS: 'SET_VOLUME_SUCCESS',
  SET_VOLUME_FAILURE: 'SET_VOLUME_FAILURE',
}

export const TRACK = {
  CHECK_TRACK_IS_FAVORITED_REQUEST: 'CHECK_TRACK_IS_FAVORITED_REQUEST',
  CHECK_TRACK_IS_FAVORITED_SUCCESS: 'CHECK_TRACK_IS_FAVORITED_SUCCESS',
  CHECK_TRACK_IS_FAVORITED_FAILURE: 'CHECK_TRACK_IS_FAVORITED_FAILURE',
  TOGGLE_FAVORITE_REQUEST: 'TOGGLE_FAVORITE_REQUEST',
  TOGGLE_FAVORITE_SUCCESS: 'TOGGLE_FAVORITE_SUCCESS',
  TOGGLE_FAVORITE_FAILURE: 'TOGGLE_FAVORITED_FAILURE'
}