export const MENU_BAR = {
  SWITCH_MENU: 'SWITCH_MENU'
}

export const PLAYER = {
  FETCH_PLAYING_TRACK_REQUEST: 'FETCH_PLAYING_TRACK_REQUEST',
  FETCH_PLAYING_TRACK_SUCCESS: 'FETCH_PLAYING_TRACK_SUCCESS',
  FETCH_PLAYING_TRACK_FAILURE: 'FETCH_PLAYING_TRACK_FAILURE'
}